server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 路由到商品微服务
    search-service: /search/** #路由到搜索微服务
    user-service: /user/**   #路由到用户微服务
    auth-service: /auth/**  #路由到授权中心微服务
    cart-service: /cart/**  #路由到购物车微服务
    order-service: /order/**  #路由到订单支付微服务
  add-host-header: true    #携带请求本身的head头信息
  sensitive-headers:   #设置默认的敏感头信息设置为空  否则默认忽略掉 cookie
leyou:
  jwt:
    pubKeyPath:  C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item